package com.hamzaelkasmi.stage.controller;

import com.hamzaelkasmi.stage.model.Conteneure;
import com.hamzaelkasmi.stage.service.ConteneureService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/api/conteneurs")
@CrossOrigin(origins = "http://localhost:3000", allowedHeaders = "*", methods = {RequestMethod.GET, RequestMethod.POST, RequestMethod.PUT, RequestMethod.DELETE, RequestMethod.OPTIONS}, allowCredentials = "true")
public class ConteneureController {

    @Autowired
    private ConteneureService conteneureService;

    @GetMapping
    public ResponseEntity<List<Conteneure>> getAllConteneures() {
        List<Conteneure> conteneures = conteneureService.getAllConteneures();
        return new ResponseEntity<>(conteneures, HttpStatus.OK);
    }

    @GetMapping("/{id}")
    public ResponseEntity<Conteneure> getConteneureById(@PathVariable("id") String id) {
        Optional<Conteneure> conteneureData = conteneureService.getConteneureById(id);
        if (conteneureData.isPresent()) {
            return new ResponseEntity<>(conteneureData.get(), HttpStatus.OK);
        } else {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    @PostMapping
    public ResponseEntity<Conteneure> createConteneure(@RequestBody Conteneure conteneure) {
        try {
            // Force ID to be null so it will be generated by the ConteneureIdGenerator
            conteneure.setId_conteneure(null);
            
            Conteneure _conteneure = conteneureService.saveConteneure(conteneure);
            return new ResponseEntity<>(_conteneure, HttpStatus.CREATED);
        } catch (Exception e) {
            return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }

    @PutMapping("/{id}")
    public ResponseEntity<Conteneure> updateConteneure(@PathVariable("id") String id, @RequestBody Conteneure conteneure) {
        Optional<Conteneure> conteneureData = conteneureService.getConteneureById(id);
        if (conteneureData.isPresent()) {
            Conteneure _conteneure = conteneureData.get();
            _conteneure.setNom_conteneure(conteneure.getNom_conteneure());
            return new ResponseEntity<>(conteneureService.saveConteneure(_conteneure), HttpStatus.OK);
        } else {
            return new ResponseEntity<>(HttpStatus.NOT_FOUND);
        }
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<HttpStatus> deleteConteneure(@PathVariable("id") String id) {
        try {
            conteneureService.deleteConteneure(id);
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
        } catch (Exception e) {
            return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
        }
    }
} 